services:
  - type: web
    name: whvid-downloader
    runtime: python
    repo: https://github.com/vimal2645/whvid-downloader
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
